export const ACTION_TYPES = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_USER_ROLE: 'SET_USER_ROLE',
    SET_USER_EXPERT: 'SET_USER_EXPERT',
    SET_ALL_USER: 'SET_ALL_USER',
    SET_ALL_DIAGNOSE: 'SET_ALL_DIAGNOSE'
}